export const msg = {
  SET_ID: 'MSG_SET_ID',
  SET_CLASS: 'MSG_SET_CLASS',
  BUZZED_STATE: 'MSG_BUZZED_STATE',
  CLR_BUZZED: 'MSG_CLR_BUZZED',
  HOST_PROMOTED: 'MSG_HOST_PROMOTED',
  ERROR: 'MSG_ERROR',
  UPDATE_CONTESTANTS: 'MSG_UPDATE_CONTESTANTS',
  HANDSHAKE: 'MSG_HANDSHAKE',
  BUZZED: 'MSG_BUZZED',
  UPDATE_CONTESTANT: 'MSG_UPDATE_CONTESTANT',
  UPDATE_CONTESTANT_FIELD: 'MSG_UPDATE_CONTESTANT_FIELD',
  ANSWER: 'MSG_ANSWER',
  QUESTION: 'MSG_QUESTION',
  CORRECT: 'MSG_CORRECT',
  INCORRECT: 'MSG_INCORRECT',
  NEXT_QUESTION: 'MSG_NEXT_QUESTION',
}

export const buzzer = {
  READY: 'READY',
  BUZZED: 'BUZZED',
  FROZEN: 'FROZEN'
};

export const CLASS_DISPLAY = 'DISPLAY';
export const CLASS_CONTESTANT = 'CONTESTANT';
export const CLASS_HOST = 'HOST';
export const CLASS_NONE = 'NONE';

export const NOT_CONNECTED = 'NOT_CONNECTED';
export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';

export const websocket = {
  URL: 'ws://localhost:8080',
  PROTOCOL: 'quiz-master'
};

export const socketActions = {
  CONNECT: 'SOCKET_ACTION_CONNECT',
};

export const actions = {
  DISCONNECT: 'ACTION_DISCONNECT',
  CONFIGURED: 'ACTION_CONFIGURED',
  CONNECT_STATUS: 'ACTION_CONNECT_STATUS',
  SET_ID: 'ACTION_SET_ID',
  UPDATE_TIMER: 'ACTION_UPDATE_TIMER',
  SET_NAME: 'ACTION_SET_NAME',
  SET_CLASS: 'ACTION_SET_CLASS',
  BUZZ: 'ACTION_BUZZ',
  BUZZED_STATE: 'ACTION_BUZZED_STATE',
  UPDATE_CONTESTANTS: 'ACTION_UPDATE_CONTESTANTS',
  UPDATE_CONTESTANT: 'ACTION_UPDATE_CONTESTANT',
  CLEAR_BUZZERS: 'ACTION_CLEAR_BUZZERS',
  UPDATE_CONTESTANT_FIELD: 'ACTION_UPDATE_CONTESTANT_FIELD',
  ANSWER: 'ACTION_ANSWER',
  QUESTION: 'ACTION_QUESTION',
  NEXT_QUESTION: 'ACTION_NEXT_QUESTION',
  ENABLE_QUESTION: 'ACTION_ENABLE_QUESTION',
  TIMER_STARTED: 'ACTION_TIMER_STARTED',
  TIMER_STOPPED: 'ACTION_TIMER_STOPPED',
  TIMER_TICK: 'ACTION_TIMER_TICK',
}

export const COLORS = [
  'red', 'green', 'blue', 'indigo', 'pink', 'purple', 'deepPurple', 'lightBlue', 'cyan', 'teal', 'lightGreen', 'lime', 'yellow', 'amber', 'orange', 'deepOrange',
  'brown', 'grey', 'blueGrey'
];
